name: Lint CSS
on: [push]

jobs:
  lint:
    runs-on: docker
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.COASTALCOMMITSTOKEN }}
    - name: Lint CSS
      uses: actions/stylelinter@master
